apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-injection
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: cluster_components/servicemesh/istio/istio-injection
    repoURL: <repoURL>
    targetRevision: <revision>
  destination:
    server: <server>
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
