apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: not-important
spec:
  source:
    path: environment_kustomizations/cinchy-nonprod/development/platform_components
    targetRevision: master
    repoURL: https://github.com/Armen024/cinchy.argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: development