apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/Armen024/
  username: Armen024
  password: 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
