apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: <<base_repo_url>>
  username: <<git_username>>
  password: <<git_password>>
